image:
  ubuntu1804

environment:
  matrix:
    - PY: 2.7
      NUMPY: 1.13
      SCIPY: 1.1
      PETSc: 3.8.1
    - PY: 3.6
      NUMPY: 1.14
      SCIPY: 1.0.1
      PETSc: 3.8.1
      UPLOAD_DOCS: 1

install:
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test;
    sudo apt-get update;
    sudo apt-get -y install gfortran;
    sudo apt-get -y install libblas-dev;
    sudo apt-get -y install liblapack-dev;
    sudo apt-get -y install libopenmpi-dev;
    sudo apt-get -y install openmpi-bin;

    echo "Building python environment...";
    wget "https://repo.continuum.io/miniconda/Miniconda${PY:0:1}-4.5.11-Linux-x86_64.sh" -O miniconda.sh;
    chmod +x miniconda.sh;
    ./miniconda.sh -b  -p $HOME/miniconda;
    export PATH=$HOME/miniconda/bin:$PATH;

    conda create --yes -n PY$PY python=$PY;
    source $HOME/miniconda/bin/activate PY$PY;

    conda install --yes numpy=$NUMPY scipy=$SCIPY cython swig nose sphinx mock;

    pip install --upgrade pip;
    pip install redbaron;
    pip install git+https://github.com/OpenMDAO/testflo.git;
    pip install coverage;
    pip install git+https://github.com/swryan/coveralls-python@work;

    git clone https://github.com/OpenMDAO/pyoptsparse.git;
    cd pyoptsparse;
    python setup.py install;
    cd ..;

    pip install mpi4py;
    pip install petsc4py==$PETSc;

    conda install --yes matplotlib;

    pip install .;
    conda list

build: off

test_script:
  - testflo . -n 1
