build: false

version: 2.0.{build}

platform:
  - x64

environment:
  matrix:
    - PYTHON: 2.7
      CONDA: "C:\\Miniconda-x64"

    - PYTHON: 3.6
      CONDA: "C:\\Miniconda36-x64"

install:
  - echo %CONDA%
  - set PATH=%CONDA%;%CONDA%\Scripts;%PATH%
  - conda config --set always_yes yes
  - conda update conda
  - conda install python=%PYTHON% numpy=1.14.2 scipy=1.0.1 nose hdf5 h5py sphinx mock pip --quiet
  - pip install redbaron
  - pip install git+https://github.com/OpenMDAO/testflo.git
  - pip install matplotlib
  - cd C:\projects\OpenMDAO*
  - pip install -e .

test_script:
  - testflo . -n 1

