build: false

version: 2.0.{build}

platform:
  - x64

environment:
  matrix:
    - PYTHON: 2.7
      CONDA: "C:\\Miniconda-x64"

    - PYTHON: 3.6
      CONDA: "C:\\Miniconda36-x64"

install:
  - echo %CONDA%
  - set PATH=%CONDA%;%CONDA%\Scripts;%PATH%
  - conda config --set always_yes yes
  - conda update conda
  - conda install python=%PYTHON% numpy scipy nose hdf5 h5py sphinx mock pip --quiet
  - pip install git+https://github.com/OpenMDAO/testflo.git
  - conda install git
  - cd C:\projects\OpenMDAO*
  - git reset --hard b715ec0dc87ad08e6169a4776dc146f2d05a1d14
  - pip install -e .


test_script:
  - testflo . -n 1

